version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=https://api.example.com
        NEXT_PUBLIC_PARSE_APPLICATION_ID = WZDEKfZlNBSTOgSELIcWN4U7OP1p2lcx1eIRQARD
        NEXT_PUBLIC_PARSE_JAVASCRIPT_KEY = IQ1eS77LC9GiqlETDCnJVyGSwT14LowSBBHKlCmp
